name: "transformer"

data:
    src: "de"
    trg: "en"
    train: "/home/nfs01/zouw/data/wmt14_en-de_processed/subword_processed/train.sub"
    dev: "/home/nfs01/zouw/data/wmt14_en-de_processed/subword_processed/newstest2013.sub"
    test: "/home/nfs01/zouw/data/wmt14_en-de_processed/subword_processed/newstest2014.sub"
    level: "bpe"
    lowercase: False
    max_sent_length: 100
    src_vocab: "/home/nfs01/zouw/data/wmt14_en-de_processed/subword_processed/vocab.txt"
    src_voc_limit: 37000
    trg_vocab: "/home/nfs01/zouw/data/wmt14_en-de_processed/subword_processed/vocab.txt"
    trg_voc_limit: 37000

testing:
    beam_size: 4
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.999]
    scheduling: "noam"
    patience: 8
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0002
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_size: 12000
    batch_type: "token"
    eval_batch_size: 3600
    eval_batch_type: "token"
    batch_multiplier: 4
    early_stopping_metric: "ppl"
    epochs: 100
    validation_freq: 4000
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "/home/nfs01/zouw/models/wmt_deen_TF_best"
    overwrite: False
    shuffle: True
    use_cuda: True
    max_output_length: 100
    print_valid_sents: [0, 1, 2, 3]
    keep_best_ckpts: 3

model:
    initializer: "xavier"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    tied_embeddings: True
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.1
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 8
        embeddings:
            embedding_dim: 512
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 512
        ff_size: 2048
        dropout: 0.1
